### ISSUE TITLE
[Evolution 3.24] Links are invisible (white on white)

### ISSUE THREAD

**Issue by HeikoAdams** [B00merang-Project/Android#1]
Using latest git master links in text-mails are invisible in evolution because it seems they are white on white background.
![bildschirmfoto von 2017-05-31 17-24-35](https://cloud.githubusercontent.com/assets/1418818/26639786/0d53816e-4626-11e7-8978-eef8f0da3390.png)

**Comment by Elbullazul** [comment]
@HeikoAdams how does it looks with another theme (arc, for example)

**Comment by HeikoAdams** [comment]
@Elbullazul with arc it looks like that
![bildschirmfoto von 2017-05-31 20-27-25](https://cloud.githubusercontent.com/assets/1418818/26647431/a19e1370-463f-11e7-9e11-9dccbfeab071.png)

**Comment by Elbullazul** [comment]
@HeikoAdams found the fix, will commit changes soon

**Comment by Elbullazul** [comment]
fixed
